name: GitHub Actions Demo
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - run: echo "The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - name: Check out repository code
        uses: actions/checkout@v2
      - run: echo "The ${{ github.repository }} repository has been cloned to the runner."
      - run: echo "The workflow is now ready to test your code on the runner."
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
          sudo apt install libpcsclite-dev pcscd socat opensc pcsc-tools
          dpkg -l
          cd src
          make -f Makefile.console
          mkdir tmp;
          socat -d -d pty,link=tmp/OsEIDsim.socket,raw,echo=0 "exec:build/console/console ...,pty,raw,echo=0" &
          PID=$!;
          sleep 1
          echo "# OsEIDsim" > tmp/reader.conf
          echo 'FRIENDLYNAME      "OsEIDsim"' >> tmp/reader.conf
          echo "DEVICENAME        ${{ github.workspace }}/src/tmp/OsEIDsim.socket" >> tmp/reader.conf
          echo "LIBPATH           ${{ github.workspace }}/src/build/console/libOsEIDsim.so.0.0.1" >> tmp/reader.conf;
          echo "CHANNELID         1" >> tmp/reader.conf
          sudo mv tmp/reader.conf /etc/reader.conf.d/reader.conf
          cat /etc/reader.conf.d/reader.conf
          sudo systemctl stop pcscd.service pcscd.socket
          sudo systemctl start pcscd.service pcscd.socket;
          opensc-tool -l
          cd ${{ github.workspace }}/tools
          echo | ./OsEID-tool INIT;
          ./OsEID-tool RSA-CREATE-KEYS;
          ./OsEID-tool RSA-UPLOAD-KEYS;
          ./OsEID-tool RSA-DECRYPT-TEST;
          kill -9 $PID;
      - run: echo "This job's status is ${{ job.status }}."
